# syntax=docker/dockerfile:1

FROM node:18-alpine
WORKDIR /app
COPY ./Aufgaben/Aufgabe1 /app
RUN yarn install --production
CMD ["node", "C:/Users/David.Schwieder/Docker/Aufgaben/Aufgabe1/src/index.js"]
EXPOSE 3000